### ISSUE TITLE
homework/4.md

### ISSUE THREAD

**Issue by rhw99** [mt4007-ht23/mt4007-ht23.github.io#9]
Hello!

I don't see any change in HW4 yet.  I was wondering about these two sentences:
"Analyse the country with highest growth rate in the last 5 years. That is, create a plot that illustrates the growth rate of the countries in the table above over the last 10 years." 
1) Should it be the last 5 or 10 years?
2) should it be the highest growth rate of all ca200 countries, or of the top five countries in phones per capita in 2019 that are supposed to be presented in a table?

Thanks!
Ryan

**Comment by taariqnazar** [comment]
This should have been fixed! Sorry for the late reply.
